[homes.bso-lenovo]
user = "bsotnikow"

[clients.hp-430-g7]
disk_id = "nvme-WDS100T1X0E-00AFY0_21413H442704"

[clients.tower-of-power]
disk_id = "nvme-eui.00000000000000000026b7685ce299b5"

[services.gitea]
host = "homelab"

[services.homepage]
host = "homelab"

[services.grafana]
host = "homelab"

[services.whats-up-docker]
host = "homelab"

[services.prometheus]
host = "homelab"

[services.coredns]
host = "homelab"

[services.caddy]
host = "homelab"

[hosts.homelab]
address = "192.168.1.50"
disk_id = "wwn-0x56479a7001514900"

[defaults.clients]
os = "nixos"
user = "cethien"

[defaults.hosts]
os = "nixos"
default_gateway = "192.168.1.1"
nameservers = ["192.168.1.1", "1.1.1.1"]


